import './loadComponent.js';
import '../header/toggleTheme.js';
import '../newsSection/rollingnews.js';
import '../main/listView/subscribe.js';
import '../header/todayDate.js';
import '../main/gridView/displaygridViewnews.js';
import '../main/listView/displaylistViewNews.js';
import '../main/gridView/initialGridView.js';
import '../main/toggleView.js';