export const allNewsData = [
    {
        category: '종합/경제',
        company: [
            {
                id: 1,
                companyId: 1,
                companyIcon: '../../images/assets/company/company_ico_1.svg',
                companyName: '서울경제',
                updatedDate: '07월 14일 09:00 직접 편집',
                mainNews: {
                    id: 1,
                    src: 'https://picsum.photos/500/300?img=1',
                    title: '한국경제, GDP 성장률 전망···경기회복 기대감',
                },
                news: [
                    { id: 1, title: '글로벌 경제 상황, 한국 경제에 미치는 영향' },
                    { id: 2, title: '수출 증가, 코로나 후 경제 회복의 주요 요소' },
                    { id: 3, title: '미국 금리 인상, 한국 경제에 미치는 영향 예상' },
                    { id: 4, title: '디지털 화폐 시장의 급성장, 금융 시장에 미치는 영향' },
                    { id: 5, title: '글로벌 인플레이션 문제, 한국 경제 전망에 대한 우려' },
                    { id: 6, title: '경제 성장률 예측, 2차 재난지원금 효과 분석' },
                ],
            },
            {
                id: 2,
                companyId: 2,
                companyIcon: '../../images/assets/company/company_ico_2.svg',
                companyName: '데일리안',
                updatedDate: '07월 15일 10:30 직접 편집',
                mainNews: {
                    id: 2,
                    src: 'https://picsum.photos/500/300?img=2',
                    title: '삼성증권, 주식 시장 전망 발표···테크주 중심의 성장 예상',
                },
                news: [
                    { id: 1, title: '테크 주식, 미래 성장의 중심' },
                    { id: 2, title: '전기차 산업, 투자자들의 관심 집중' },
                    { id: 3, title: '반도체 업황 개선, 주가에 미치는 영향' },
                    { id: 4, title: '클라우드 컴퓨팅 시장, 성장 가능성과 리스크' },
                    { id: 5, title: '그린 에너지 기업들의 주가 동향' },
                    { id: 6, title: '주식 시장의 변동성 요인 분석' },
                ],
            },
            {
                id: 3,
                companyId: 3,
                companyIcon: '../../images/assets/company/company_ico_3.svg',
                companyName: '헤럴드경제',
                updatedDate: '07월 16일 11:45 직접 편집',
                mainNews: {
                    id: 3,
                    src: 'https://picsum.photos/500/300?img=3',
                    title: '한국은행, 금리 인상 결정···경기 부양과 물가 안정 추진',
                },
                news: [
                    { id: 1, title: '금리 인상과 한국 경제에 대한 전망' },
                    { id: 2, title: '부동산 시장, 금리 인상에 따른 영향' },
                    { id: 3, title: '외환 시장의 변동성과 금리 정책의 관계' },
                    { id: 4, title: '통화정책의 변화와 기업들의 대응 전략' },
                    { id: 5, title: '물가 상승률과 소비자 심리' },
                    { id: 6, title: '경제 성장률과 정부의 경제 정책' },
                ],
            },
            {
                id: 4,
                companyId: 4,
                companyIcon: '../../images/assets/company/company_ico_4.svg',
                companyName: 'SBS Biz',
                updatedDate: '07월 17일 14:20 직접 편집',
                mainNews: {
                    id: 4,
                    src: 'https://picsum.photos/500/300?img=4',
                    title: '현대차, 전기차 시장 공략 확대···글로벌 판매 전망',
                },
                news: [
                    { id: 1, title: '전기차 시장의 성장과 현대차의 전략' },
                    { id: 2, title: '글로벌 경쟁에서의 현대차의 경쟁력' },
                    { id: 3, title: '배터리 기술 발전과 전기차의 성능 개선' },
                    { id: 4, title: '환경 규제와 자동차 산업의 변화' },
                    { id: 5, title: '글로벌 시장에서의 전기차 수요 예측' },
                    { id: 6, title: '자율주행 기술과의 통합을 통한 현대차의 전략' },
                ],
            },
            {
                id: 5,
                companyId: 5,
                companyIcon: '../../images/assets/company/company_ico_5.svg',
                companyName: '세계일보',
                updatedDate: '07월 18일 15:30 직접 편집',
                mainNews: {
                    id: 5,
                    src: 'https://picsum.photos/500/300?img=15',
                    title: '기아자동차, 신모델 발표···디자인과 기술혁신 강화',
                },
                news: [
                    { id: 1, title: '기아자동차의 신모델과 시장 반응' },
                    { id: 2, title: '디자인 혁신과 기아자동차의 브랜드 전략' },
                    { id: 3, title: '기술 혁신과 전기차 시장 공략 전략' },
                    { id: 4, title: '글로벌 시장에서의 기아자동차의 경쟁력' },
                    { id: 5, title: '자율주행 기술 도입 계획과 전망' },
                    { id: 6, title: '환경 친화적인 기아자동차의 향후 전망' },
                ],
            },
            {
                id: 6,
                companyId: 6,
                companyIcon: '../../images/assets/company/company_ico_6.svg',
                companyName: '아시아경제',
                updatedDate: '07월 19일 16:45 직접 편집',
                mainNews: {
                    id: 6,
                    src: 'https://picsum.photos/500/300?img=6',
                    title: '네이버페이, 디지털 화폐 시장 진출···결제 시장 재편 예고',
                },
                news: [
                    { id: 1, title: '디지털 화폐 시장의 성장과 네이버페이의 전략' },
                    { id: 2, title: '결제 시장의 혁신과 경쟁' },
                    { id: 3, title: '블록체인 기술의 활용과 향후 전망' },
                    { id: 4, title: '정부의 디지털 화폐 정책과 산업의 반응' },
                    { id: 5, title: '소비자의 디지털 화폐 사용 경향과 변화' },
                    { id: 6, title: '네이버페이의 글로벌 시장 진출 전략' },
                ],
            },
            {
                id: 7,
                companyId: 7,
                companyIcon: '../../images/assets/company/company_ico_7.svg',
                companyName: '이데일리',
                updatedDate: '07월 20일 17:00 직접 편집',
                mainNews: {
                    id: 7,
                    src: 'https://picsum.photos/500/300?img=7',
                    title: '카카오뱅크, 디지털 금융 시장 공략···새로운 서비스 출시 계획',
                },
                news: [
                    { id: 1, title: '디지털 금융 시장의 성장과 카카오뱅크의 전략' },
                    { id: 2, title: '핀테크 기업들의 협업과 경쟁' },
                    { id: 3, title: '정보보안과 디지털 금융의 연계' },
                    { id: 4, title: '카카오뱅크의 디지털 전환 전략' },
                    { id: 5, title: '정부의 디지털 금융 정책과 산업의 대응' },
                    { id: 6, title: '카카오뱅크의 글로벌 시장 진출 전략' },
                ],
            },
            {
                id: 8,
                companyId: 8,
                companyIcon: '../../images/assets/company/company_ico_8.svg',
                companyName: '한국일보',
                updatedDate: '07월 21일 18:15 직접 편집',
                mainNews: {
                    id: 18,
                    src: 'https://picsum.photos/500/300?img=8',
                    title: '현대모비스, 자율주행차 기술 개발···미래 모빌리티 시장 선도',
                },
                news: [
                    { id: 1, title: '자율주행차 기술의 발전과 현대모비스의 기술 혁신' },
                    { id: 2, title: '미래 모빌리티 시장에서의 경쟁력 확보 전략' },
                    { id: 3, title: '센서 기술의 발전과 자율주행차 성능 개선' },
                    { id: 4, title: '환경 친화적 자율주행차의 설계 및 개발' },
                    { id: 5, title: '글로벌 자동차 제조사들과의 협력과 경쟁' },
                    { id: 6, title: '현대모비스의 미래 기술 전망과 전략' },
                ],
            },
            {
                id: 9,
                companyId: 9,
                companyIcon: '../../images/assets/company/company_ico_9.svg',
                companyName: '아이뉴스24',
                updatedDate: '07월 22일 19:30 직접 편집',
                mainNews: {
                    id: 9,
                    src: 'https://picsum.photos/500/300?img=9',
                    title: '기업 구조조정, 코로나19 여파로 늘어난 M&A 활동',
                },
                news: [
                    { id: 1, title: '글로벌 M&A 시장의 활성화와 한국 기업들의 참여' },
                    { id: 2, title: '디지털 산업과 관련된 M&A 활동 증가' },
                    { id: 3, title: '투자 의사결정의 변화와 M&A 활동의 경제적 영향' },
                    { id: 4, title: '산업 구조조정과 M&A의 경쟁 전략' },
                    { id: 5, title: '통합 관리와 성과 평가' },
                    { id: 6, title: '기업 문화 통합과 인적 자원 관리' },
                ],
            },
            {
                id: 10,
                companyId: 10,
                companyIcon: '../../images/assets/company/company_ico_10.svg',
                companyName: '파이낸셜뉴스',
                updatedDate: '07월 23일 20:45 직접 편집',
                mainNews: {
                    id: 10,
                    src: 'https://picsum.photos/500/300?img=10',
                    title: '금융기술 기업들의 디지털 전환, 금융 서비스 혁신',
                },
                news: [
                    { id: 1, title: '금융 서비스의 디지털 전환과 고객 경험 개선' },
                    { id: 2, title: '인공지능과 빅데이터 기술의 금융 서비스 적용' },
                    { id: 3, title: '블록체인 기술의 금융 시장 적용 사례' },
                    { id: 4, title: '금융 모바일 앱의 사용 증가와 보안 문제' },
                    { id: 5, title: '금융 시장의 경제적 불균형과 금융 서비스의 조정' },
                    { id: 6, title: '기업의 디지털 전환 전략과 투자자들의 반응' },
                ],
            },
            {
                id: 11,
                companyId: 11,
                companyIcon: '../../images/assets/company/company_ico_11.svg',
                companyName: '스포츠서울',
                updatedDate: '07월 14일 09:00 직접 편집',
                mainNews: {
                    id: 11,
                    src: 'https://picsum.photos/500/300?img=11',
                    title: '한국경제, GDP 성장률 전망···경기회복 기대감',
                },
                news: [
                    { id: 1, title: '글로벌 경제 상황, 한국 경제에 미치는 영향' },
                    { id: 2, title: '수출 증가, 코로나 후 경제 회복의 주요 요소' },
                    { id: 3, title: '미국 금리 인상, 한국 경제에 미치는 영향 예상' },
                    { id: 4, title: '디지털 화폐 시장의 급성장, 금융 시장에 미치는 영향' },
                    { id: 5, title: '글로벌 인플레이션 문제, 한국 경제 전망에 대한 우려' },
                    { id: 6, title: '경제 성장률 예측, 2차 재난지원금 효과 분석' },
                ],
            },
            {
                id: 12,
                companyId: 12,
                companyIcon: '../../images/assets/company/company_ico_12.svg',
                companyName: '스포츠동아',
                updatedDate: '07월 15일 10:30 직접 편집',
                mainNews: {
                    id: 12,
                    src: 'https://picsum.photos/500/300?img=12',
                    title: '삼성증권, 주식 시장 전망 발표···테크주 중심의 성장 예상',
                },
                news: [
                    { id: 1, title: '테크 주식, 미래 성장의 중심' },
                    { id: 2, title: '전기차 산업, 투자자들의 관심 집중' },
                    { id: 3, title: '반도체 업황 개선, 주가에 미치는 영향' },
                    { id: 4, title: '클라우드 컴퓨팅 시장, 성장 가능성과 리스크' },
                    { id: 5, title: '그린 에너지 기업들의 주가 동향' },
                    { id: 6, title: '주식 시장의 변동성 요인 분석' },
                ],
            },
            {
                id: 13,
                companyId: 13,
                companyIcon: '../../images/assets/company/company_ico_13.svg',
                companyName: '석간문화일보',
                updatedDate: '07월 16일 11:45 직접 편집',
                mainNews: {
                    id: 13,
                    src: 'https://picsum.photos/500/300?img=13',
                    title: '한국은행, 금리 인상 결정···경기 부양과 물가 안정 추진',
                },
                news: [
                    { id: 1, title: '금리 인상과 한국 경제에 대한 전망' },
                    { id: 2, title: '부동산 시장, 금리 인상에 따른 영향' },
                    { id: 3, title: '외환 시장의 변동성과 금리 정책의 관계' },
                    { id: 4, title: '통화정책의 변화와 기업들의 대응 전략' },
                    { id: 5, title: '물가 상승률과 소비자 심리' },
                    { id: 6, title: '경제 성장률과 정부의 경제 정책' },
                ],
            },
            {
                id: 14,
                companyId: 14,
                companyIcon: '../../images/assets/company/company_ico_14.svg',
                companyName: 'KBS WORLD',
                updatedDate: '07월 17일 14:20 직접 편집',
                mainNews: {
                    id: 14,
                    src: 'https://picsum.photos/500/300?img=14',
                    title: '현대차, 전기차 시장 공략 확대···글로벌 판매 전망',
                },
                news: [
                    { id: 1, title: '전기차 시장의 성장과 현대차의 전략' },
                    { id: 2, title: '글로벌 경쟁에서의 현대차의 경쟁력' },
                    { id: 3, title: '배터리 기술 발전과 전기차의 성능 개선' },
                    { id: 4, title: '환경 규제와 자동차 산업의 변화' },
                    { id: 5, title: '글로벌 시장에서의 전기차 수요 예측' },
                    { id: 6, title: '자율주행 기술과의 통합을 통한 현대차의 전략' },
                ],
            },
            {
                id: 15,
                companyId: 15,
                companyIcon: '../../images/assets/company/company_ico_15.svg',
                companyName: 'Korea JoongAng Daily',
                updatedDate: '07월 18일 15:30 직접 편집',
                mainNews: {
                    id: 15,
                    src: 'https://picsum.photos/500/300?img=15',
                    title: '기아자동차, 신모델 발표···디자인과 기술혁신 강화',
                },
                news: [
                    { id: 1, title: '기아자동차의 신모델과 시장 반응' },
                    { id: 2, title: '디자인 혁신과 기아자동차의 브랜드 전략' },
                    { id: 3, title: '기술 혁신과 전기차 시장 공략 전략' },
                    { id: 4, title: '글로벌 시장에서의 기아자동차의 경쟁력' },
                    { id: 5, title: '자율주행 기술 도입 계획과 전망' },
                    { id: 6, title: '환경 친화적인 기아자동차의 향후 전망' },
                ],
            },
            {
                id: 16,
                companyId: 16,
                companyIcon: '../../images/assets/company/company_ico_16.svg',
                companyName: 'Insight',
                updatedDate: '07월 19일 16:45 직접 편집',
                mainNews: {
                    id: 16,
                    src: 'https://picsum.photos/500/300?img=16',
                    title: '네이버페이, 디지털 화폐 시장 진출···결제 시장 재편 예고',
                },
                news: [
                    { id: 1, title: '디지털 화폐 시장의 성장과 네이버페이의 전략' },
                    { id: 2, title: '결제 시장의 혁신과 경쟁' },
                    { id: 3, title: '블록체인 기술의 활용과 향후 전망' },
                    { id: 4, title: '정부의 디지털 화폐 정책과 산업의 반응' },
                    { id: 5, title: '소비자의 디지털 화폐 사용 경향과 변화' },
                    { id: 6, title: '네이버페이의 글로벌 시장 진출 전략' },
                ],
            },
            {
                id: 17,
                companyId: 17,
                companyIcon: '../../images/assets/company/company_ico_17.svg',
                companyName: '법률방송뉴스',
                updatedDate: '07월 20일 17:00 직접 편집',
                mainNews: {
                    id: 17,
                    src: 'https://picsum.photos/500/300?img=17',
                    title: '카카오뱅크, 디지털 금융 시장 공략···새로운 서비스 출시 계획',
                },
                news: [
                    { id: 1, title: '디지털 금융 시장의 성장과 카카오뱅크의 전략' },
                    { id: 2, title: '핀테크 기업들의 협업과 경쟁' },
                    { id: 3, title: '정보보안과 디지털 금융의 연계' },
                    { id: 4, title: '카카오뱅크의 디지털 전환 전략' },
                    { id: 5, title: '정부의 디지털 금융 정책과 산업의 대응' },
                    { id: 6, title: '카카오뱅크의 글로벌 시장 진출 전략' },
                ],
            },
            {
                id: 18,
                companyId: 18,
                companyIcon: '../../images/assets/company/company_ico_18.svg',
                companyName: '시사저널',
                updatedDate: '07월 21일 18:15 직접 편집',
                mainNews: {
                    id: 18,
                    src: 'https://picsum.photos/500/300?img=18',
                    title: '현대모비스, 자율주행차 기술 개발···미래 모빌리티 시장 선도',
                },
                news: [
                    { id: 1, title: '자율주행차 기술의 발전과 현대모비스의 기술 혁신' },
                    { id: 2, title: '미래 모빌리티 시장에서의 경쟁력 확보 전략' },
                    { id: 3, title: '센서 기술의 발전과 자율주행차 성능 개선' },
                    { id: 4, title: '환경 친화적 자율주행차의 설계 및 개발' },
                    { id: 5, title: '글로벌 자동차 제조사들과의 협력과 경쟁' },
                    { id: 6, title: '현대모비스의 미래 기술 전망과 전략' },
                ],
            },
            {
                id: 19,
                companyId: 19,
                companyIcon: '../../images/assets/company/company_ico_19.svg',
                companyName: 'RBS한국농어촌방송',
                updatedDate: '07월 22일 19:30 직접 편집',
                mainNews: {
                    id: 19,
                    src: 'https://picsum.photos/500/300?img=19',
                    title: '기업 구조조정, 코로나19 여파로 늘어난 M&A 활동',
                },
                news: [
                    { id: 1, title: '글로벌 M&A 시장의 활성화와 한국 기업들의 참여' },
                    { id: 2, title: '디지털 산업과 관련된 M&A 활동 증가' },
                    { id: 3, title: '투자 의사결정의 변화와 M&A 활동의 경제적 영향' },
                    { id: 4, title: '산업 구조조정과 M&A의 경쟁 전략' },
                    { id: 5, title: '통합 관리와 성과 평가' },
                    { id: 6, title: '기업 문화 통합과 인적 자원 관리' },
                ],
            },
            {
                id: 20,
                companyId: 20,
                companyIcon: '../../images/assets/company/company_ico_20.svg',
                companyName: '조이뉴스24',
                updatedDate: '07월 23일 20:45 직접 편집',
                mainNews: {
                    id: 20,
                    src: 'https://picsum.photos/500/300?img=20',
                    title: '금융기술 기업들의 디지털 전환, 금융 서비스 혁신',
                },
                news: [
                    { id: 1, title: '금융 서비스의 디지털 전환과 고객 경험 개선' },
                    { id: 2, title: '인공지능과 빅데이터 기술의 금융 서비스 적용' },
                    { id: 3, title: '블록체인 기술의 금융 시장 적용 사례' },
                    { id: 4, title: '금융 모바일 앱의 사용 증가와 보안 문제' },
                    { id: 5, title: '금융 시장의 경제적 불균형과 금융 서비스의 조정' },
                    { id: 6, title: '기업의 디지털 전환 전략과 투자자들의 반응' },
                ],
            },
            {
                id: 21,
                companyId: 21,
                companyIcon: '../../images/assets/company/company_ico_21.svg',
                companyName: '에너지경제',
                updatedDate: '07월 24일 21:00 직접 편집',
                mainNews: {
                    id: 21,
                    src: 'https://picsum.photos/500/300?img=21',
                    title: '글로벌 수출 증가, 산업 구조 변화와 경제 성장',
                },
                news: [
                    { id: 1, title: '세계 경제의 회복과 수출 증가' },
                    { id: 2, title: '금융 시장의 변화와 글로벌 수출 시장의 영향' },
                    { id: 3, title: '무역 정책과 글로벌 경제 성장 전망' },
                    { id: 4, title: '디지털 무역 플랫폼의 성장과 산업 구조 변화' },
                    { id: 5, title: '글로벌 경제 회복과 자원 공급 망 강화' },
                    { id: 6, title: '환경 친화적 무역 정책의 추진과 산업의 변화' },
                ],
            },
            {
                id: 22,
                companyId: 22,
                companyIcon: '../../images/assets/company/company_ico_22.svg',
                companyName: 'BUSINESS POST',
                updatedDate: '07월 25일 22:15 직접 편집',
                mainNews: {
                    id: 22,
                    src: 'https://picsum.photos/500/300?img=22',
                    title: '에너지 산업, 탄소 중립 추진과 투자 확대',
                },
                news: [
                    { id: 1, title: '신재생 에너지의 증가와 에너지 전환 시장의 변화' },
                    { id: 2, title: '탄소 중립의 경제적 효과와 정책의 적용' },
                    { id: 3, title: '에너지 기술의 혁신과 투자 가능성' },
                    { id: 4, title: '에너지 절약 기술과 산업적 적용' },
                    { id: 5, title: '글로벌 기업들의 탄소 중립 전략과 결과' },
                    { id: 6, title: '환경 친화적 에너지 산업의 경제적 효과와 리스크' },
                ],
            },
            {
                id: 23,
                companyId: 23,
                companyIcon: '../../images/assets/company/company_ico_23.svg',
                companyName: 'CEO스코어데일리',
                updatedDate: '07월 26일 23:30 직접 편집',
                mainNews: {
                    id: 23,
                    src: 'https://picsum.photos/500/300?img=23',
                    title: '코로나19 이후 소비 트렌드 변화와 소매업의 대응 전략',
                },
                news: [
                    { id: 1, title: '소비자 심리 변화와 소매업의 전자 상거래 전환' },
                    { id: 2, title: '코로나19 이후의 온라인 쇼핑 트렌드' },
                    { id: 3, title: '소매업체들의 디지털 마케팅 전략' },
                    { id: 4, title: '소비자 경험 개선과 리뷰 마케팅' },
                    { id: 5, title: '글로벌 소매 시장의 성장과 코로나19 이후 전망' },
                    { id: 6, title: '정부의 소비 활성화 정책과 소매업체들의 협력' },
                ],
            },
            {
                id: 24,
                companyId: 24,
                companyIcon: '../../images/assets/company/company_ico_24.svg',
                companyName: 'KNN',
                updatedDate: '07월 27일 09:30 직접 편집',
                mainNews: {
                    id: 24,
                    src: 'https://picsum.photos/500/300?img=24',
                    title: '블록체인 기술의 금융 시장 적용과 미래 전망',
                },
                news: [
                    { id: 1, title: '디지털 자산 시장의 확장과 블록체인 기술의 중요성' },
                    { id: 2, title: '중앙은행 디지털 통화의 발전과 금융 시장의 변화' },
                    { id: 3, title: '스마트 계약 기술의 활용과 금융 서비스의 혁신' },
                    { id: 4, title: '블록체인 기술의 금융 거래 속도 개선과 보안 문제' },
                    { id: 5, title: '글로벌 금융 기업들의 블록체인 기술 도입 전략' },
                    { id: 6, title: '정부의 블록체인 정책과 금융 산업의 반응' },
                ],
            },
            {
                id: 25,
                companyId: 25,
                companyIcon: '../../images/assets/company/company_ico_25.svg',
                companyName: 'The Korea Herald',
                updatedDate: '07월 28일 10:45 직접 편집',
                mainNews: {
                    id: 25,
                    src: 'https://picsum.photos/500/300?img=25',
                    title: '정부의 그린 뉴딜 정책, 산업과 기업에 미치는 영향',
                },
                news: [
                    { id: 1, title: '그린 뉴딜 정책의 목표와 실행 계획' },
                    { id: 2, title: '신재생 에너지 산업의 성장과 산업 구조 변화' },
                    { id: 3, title: '정부 지원과 투자 환경 개선' },
                    { id: 4, title: '환경 기업들의 성장과 기회' },
                    { id: 5, title: '정부와 기업의 협력과 전략' },
                    { id: 6, title: '글로벌 그린 시장의 성장과 경쟁력' },
                ],
            },
            {
                id: 26,
                companyId: 26,
                companyIcon: '../../images/assets/company/company_ico_26.svg',
                companyName: 'MBC',
                updatedDate: '07월 29일 11:00 직접 편집',
                mainNews: {
                    id: 26,
                    src: 'https://picsum.photos/500/300?img=26',
                    title: '글로벌 경제 회복 속도, 코로나19 여파와 중소기업의 전망',
                },
                news: [
                    { id: 1, title: '중소기업들의 경제 회복 속도와 현지 정부의 지원' },
                    { id: 2, title: '글로벌 공급망의 회복과 중소기업들의 재고 관리 전략' },
                    { id: 3, title: '글로벌 시장의 변동성과 수출 중소기업들의 대응' },
                    { id: 4, title: '디지털 전환과 중소기업들의 경쟁력 강화' },
                    { id: 5, title: '혁신적 솔루션과 중소기업들의 새로운 기회' },
                    { id: 6, title: '글로벌 경제 회복과 중소기업들의 글로벌 시장 진출 전략' },
                ],
            },
            {
                id: 27,
                companyId: 27,
                companyIcon: '../../images/assets/company/company_ico_27.svg',
                companyName: '뉴스타파',
                updatedDate: '07월 30일 12:15 직접 편집',
                mainNews: {
                    id: 27,
                    src: 'https://picsum.photos/500/300?img=27',
                    title: '글로벌 재택근무 트렌드, 기업과 직원들에게 미치는 영향',
                },
                news: [
                    { id: 1, title: '재택근무의 생산성과 직원들의 직업 만족도' },
                    { id: 2, title: '디지털 혁신과 재택근무의 성공적 조화' },
                    { id: 3, title: 'IT 인프라 개선과 재택근무의 효율성' },
                    { id: 4, title: '재택근무의 장단점과 노동 시장의 변화' },
                    { id: 5, title: '글로벌 기업들의 재택근무 정책과 효과적 운영' },
                    { id: 6, title: '재택근무 관련 법적 문제와 대응 전략' },
                ],
            },
            {
                id: 28,
                companyId: 28,
                companyIcon: '../../images/assets/company/company_ico_28.svg',
                companyName: 'NewDaily',
                updatedDate: '07월 31일 13:30 직접 편집',
                mainNews: {
                    id: 28,
                    src: 'https://picsum.photos/500/300?img=28',
                    title: '글로벌 소프트웨어 시장의 성장, 인공지능과 데이터 분석의 역할',
                },
                news: [
                    { id: 1, title: '글로벌 소프트웨어 시장의 크기와 성장률' },
                    { id: 2, title: '인공지능 기술의 글로벌 소프트웨어 시장 적용 사례' },
                    { id: 3, title: '빅데이터 분석과 소프트웨어 개발의 혁신' },
                    { id: 4, title: '글로벌 디지털 시장의 경쟁과 인공지능 소프트웨어 기업들' },
                    { id: 5, title: 'IT 기술과 소프트웨어 시장의 경제적 기여' },
                    { id: 6, title: '글로벌 인재와 소프트웨어 기술의 협력' },
                ],
            },
            {
                id: 29,
                companyId: 29,
                companyIcon: '../../images/assets/company/company_ico_29.svg',
                companyName: '국민일보',
                updatedDate: '08월 01일 14:45 직접 편집',
                mainNews: {
                    id: 29,
                    src: 'https://picsum.photos/500/300?img=29',
                    title: '글로벌 정치 경제의 불확실성과 기업의 리스크 관리 전략',
                },
                news: [
                    { id: 1, title: '정치 경제의 불확실성과 기업의 리스크 관리 전략' },
                    { id: 2, title: '글로벌 시장의 불확실성과 기업의 리스크 관리 전략' },
                    { id: 3, title: '기업 리스크 관리의 최신 트렌드' },
                    { id: 4, title: '불확실한 시장 환경에서의 자산 포트폴리오 관리' },
                    { id: 5, title: '글로벌 경제 회복과 기업 리스크 관리 전략' },
                    { id: 6, title: '위험 평가와 보험의 중요성' },
                ],
            },
            {
                id: 30,
                companyId: 30,
                companyIcon: '../../images/assets/company/company_ico_30.svg',
                companyName: '일간스포츠',
                updatedDate: '08월 02일 15:00 직접 편집',
                mainNews: {
                    id: 30,
                    src: 'https://picsum.photos/500/300?img=30',
                    title: '글로벌 연구 협력의 중요성과 기술 혁신의 성장',
                },
                news: [
                    { id: 1, title: '연구 개발 투자와 글로벌 기술 혁신의 성장' },
                    { id: 2, title: '인공지능 기술과 데이터 분석의 협업 사례' },
                    { id: 3, title: '글로벌 기술 혁신 네트워크와 경쟁' },
                    { id: 4, title: '신제품 개발과 시장 출시 전략' },
                    { id: 5, title: '글로벌 연구 협력의 중요성과 기술 혁신의 경제적 영향' },
                    { id: 6, title: '기술 발전과 정부 정책의 협력' },
                ],
            },
        ],
    },
    {
        category: '방송/통신',
        company: [
            {
                id: 1,
                companyId: 31,
                companyIcon: '../../images/assets/company/company_ico_31.svg',
                companyName: '경향신문',
                updatedDate: '08월 03일 16:00 직접 편집',
                mainNews: {
                    id: 31,
                    src: 'https://picsum.photos/500/300?img=31',
                    title: '5G 기술의 글로벌 보급과 통신 시장의 변화',
                },
                news: [
                    { id: 1, title: '5G 네트워크의 성과와 통신 사업자들의 경쟁' },
                    { id: 2, title: '스마트폰 시장의 5G 수요 증가' },
                    { id: 3, title: '인터넷 속도 개선과 사용자 경험' },
                    { id: 4, title: '글로벌 통신 시장의 경쟁과 전략' },
                    { id: 5, title: '새로운 IoT 기술과 통신 인프라 요구' },
                    { id: 6, title: '글로벌 통신 시장의 보안 문제와 대응 전략' },
                ],
            },
            {
                id: 2,
                companyId: 32,
                companyIcon: '../../images/assets/company/company_ico_32.svg',
                companyName: 'ZDNet Korea',
                updatedDate: '08월 04일 17:00 직접 편집',
                mainNews: {
                    id: 32,
                    src: 'https://picsum.photos/500/300?img=32',
                    title: 'OTT 서비스의 급성장과 방송 산업의 변화',
                },
                news: [
                    { id: 1, title: 'OTT 플랫폼의 구독자 수 증가와 컨텐츠 다양성' },
                    { id: 2, title: '전통 방송 산업과의 경쟁과 협력' },
                    { id: 3, title: '글로벌 스트리밍 시장의 성장과 전망' },
                    { id: 4, title: '콘텐츠 저작권 문제와 해결 방안' },
                    { id: 5, title: 'OTT 플랫폼의 기술적 발전과 사용자 경험' },
                    { id: 6, title: '정부의 OTT 규제와 산업 대응 전략' },
                ],
            },
            {
                id: 3,
                companyId: 33,
                companyIcon: '../../images/assets/company/company_ico_33.svg',
                companyName: '마이데일리',
                updatedDate: '08월 05일 18:00 직접 편집',
                mainNews: {
                    id: 33,
                    src: 'https://picsum.photos/500/300?img=33',
                    title: '클라우드 기술의 발전과 통신 네트워크의 혁신',
                },
                news: [
                    { id: 1, title: '클라우드 서비스의 성장과 기업의 디지털 전환' },
                    { id: 2, title: '5G 기반 클라우드 네트워크의 확장과 보안' },
                    { id: 3, title: '클라우드 컴퓨팅의 비즈니스 장점과 효율성' },
                    { id: 4, title: '글로벌 데이터 보호와 개인정보 보안' },
                    { id: 5, title: '하이브리드 클라우드 환경과 IT 인프라 관리' },
                    { id: 6, title: '5G 기술과 클라우드 네트워크의 통합 전략' },
                ],
            },
            {
                id: 4,
                companyId: 34,
                companyIcon: '../../images/assets/company/company_ico_34.svg',
                companyName: '머니투데이',
                updatedDate: '08월 06일 19:00 직접 편집',
                mainNews: {
                    id: 34,
                    src: 'https://picsum.photos/500/300?img=34',
                    title: '통신 보안의 중요성과 5G 네트워크의 새로운 도전',
                },
                news: [
                    { id: 1, title: '5G 네트워크 보안의 필요성과 도전 과제' },
                    { id: 2, title: '사이버 공격과 네트워크 보안 전략' },
                    { id: 3, title: '다중 클라우드 환경과 보안 인프라' },
                    { id: 4, title: '글로벌 통신 사업자들의 보안 정책' },
                    { id: 5, title: '개인정보 보호와 GDPR 준수' },
                    { id: 6, title: '5G 네트워크와 IoT 보안의 통합 관리' },
                ],
            },
            {
                id: 5,
                companyId: 35,
                companyIcon: '../../images/assets/company/company_ico_35.svg',
                companyName: 'SBS',
                updatedDate: '08월 07일 20:00 직접 편집',
                mainNews: {
                    id: 35,
                    src: 'https://picsum.photos/500/300?img=35',
                    title: '인공지능 기술과 통신 산업의 글로벌 시장 전망',
                },
                news: [
                    { id: 1, title: 'AI 기반 네트워크 관리 시스템의 발전과 전망' },
                    { id: 2, title: '자율 주행차와 통신 네트워크의 통합' },
                    { id: 3, title: 'AI 알고리즘과 네트워크 최적화 기술' },
                    { id: 4, title: '클라우드 AI 플랫폼의 글로벌 적용 사례' },
                    { id: 5, title: 'AI 보안과 통신 데이터 분석의 발전' },
                    { id: 6, title: 'AI 기반 서비스와 사용자 경험 개선 전략' },
                ],
            },
            {
                id: 6,
                companyId: 36,
                companyIcon: '../../images/assets/company/company_ico_36.svg',
                companyName: 'OhMyNews',
                updatedDate: '08월 08일 21:00 직접 편집',
                mainNews: {
                    id: 36,
                    src: 'https://picsum.photos/500/300?img=36',
                    title: '통신 기술의 혁신과 글로벌 경쟁력 강화',
                },
                news: [
                    { id: 1, title: '네트워크 가상화와 통신 비용 절감' },
                    { id: 2, title: '글로벌 5G 표준화와 산업 협력' },
                    { id: 3, title: '다음 세대 네트워크 기술의 발전 방향' },
                    { id: 4, title: '통신 장비 기업들의 기술 혁신 전략' },
                    { id: 5, title: '5G 네트워크와 스마트 시티 연계 기술' },
                    { id: 6, title: '보안과 네트워크 운영의 최신 기술 동향' },
                ],
            },
            {
                id: 7,
                companyId: 37,
                companyIcon: '../../images/assets/company/company_ico_37.svg',
                companyName: '매일경제',
                updatedDate: '08월 09일 22:00 직접 편집',
                mainNews: {
                    id: 37,
                    src: 'https://picsum.photos/500/300?img=37',
                    title: '디지털 방송 콘텐츠의 글로벌 시장 성장과 도전 과제',
                },
                news: [
                    { id: 1, title: 'OTT 플랫폼의 다양한 컨텐츠 전략과 시장 반응' },
                    { id: 2, title: '디지털 방송 규제와 콘텐츠 저작권 보호' },
                    { id: 3, title: '글로벌 스트리밍 서비스의 지역화 전략' },
                    { id: 4, title: '통신 인프라의 디지털 방송 시스템 통합' },
                    { id: 5, title: '인공지능 기반 콘텐츠 추천 시스템의 발전' },
                    { id: 6, title: '디지털 미디어와 광고 시장의 경쟁 동향' },
                ],
            },
            {
                id: 8,
                companyId: 38,
                companyIcon: '../../images/assets/company/company_ico_38.svg',
                companyName: 'MBN',
                updatedDate: '08월 10일 23:00 직접 편집',
                mainNews: {
                    id: 38,
                    src: 'https://picsum.photos/500/300?img=38',
                    title: '인공지능 기술과 통신 네트워크의 통합 시스템',
                },
                news: [
                    { id: 1, title: 'AI 기반 네트워크 관리와 효율적 자원 할당' },
                    { id: 2, title: '5G 네트워크의 AI 최적화 기술' },
                    { id: 3, title: '클라우드 플랫폼과 AI 기술의 융합' },
                    { id: 4, title: 'AI 기술과 네트워크 보안의 연구 동향' },
                    { id: 5, title: 'AI 기반 네트워크 솔루션의 글로벌 시장 전망' },
                    { id: 6, title: '인공지능과 IoT 기술의 네트워크 활용 사례' },
                ],
            },
            {
                id: 9,
                companyId: 39,
                companyIcon: '../../images/assets/company/company_ico_39.svg',
                companyName: 'YTN',
                updatedDate: '08월 11일 00:00 직접 편집',
                mainNews: {
                    id: 39,
                    src: 'https://picsum.photos/500/300?img=39',
                    title: '글로벌 통신 시장의 5G 전략과 IoT 기술 적용',
                },
                news: [
                    { id: 1, title: '5G 네트워크의 전 세계적 확산과 기술적 도전 과제' },
                    { id: 2, title: 'IoT 기술의 발전과 5G 네트워크의 상호 작용' },
                    { id: 3, title: '글로벌 통신 사업자들의 5G 투자 전략' },
                    { id: 4, title: '5G 네트워크와 스마트 시티의 통합' },
                    { id: 5, title: '5G 네트워크와 사물인터넷 보안의 중요성' },
                    { id: 6, title: '미래의 네트워크 인프라와 통신 기술 혁신' },
                ],
            },
            {
                id: 10,
                companyId: 40,
                companyIcon: '../../images/assets/company/company_ico_40.svg',
                companyName: '시사위크',
                updatedDate: '08월 12일 01:00 직접 편집',
                mainNews: {
                    id: 40,
                    src: 'https://picsum.photos/500/300?img=40',
                    title: '디지털 통신 기술과 5G 네트워크의 보안 전략',
                },
                news: [
                    { id: 1, title: '5G 네트워크 보안의 최신 기술 발전' },
                    { id: 2, title: '사이버 위협과 네트워크 보안 대응 전략' },
                    { id: 3, title: '글로벌 통신 산업의 디지털 보안 인프라' },
                    { id: 4, title: '클라우드 기반 통신 보안 솔루션' },
                    { id: 5, title: '5G 네트워크의 새로운 보안 취약점 분석' },
                    { id: 6, title: '인공지능 기반 네트워크 보안 시스템' },
                ],
            },
            {
                id: 11,
                companyId: 41,
                companyIcon: '../../images/assets/company/company_ico_41.svg',
                companyName: 'Digital Today',
                updatedDate: '08월 13일 02:00 직접 편집',
                mainNews: {
                    id: 41,
                    src: 'https://picsum.photos/500/300?img=41',
                    title: '글로벌 디지털 미디어 시장의 성장과 전망',
                },
                news: [
                    { id: 1, title: '디지털 미디어 플랫폼의 글로벌 시장 확장' },
                    { id: 2, title: '스마트 TV와 디지털 미디어 콘텐츠 시장 성장' },
                    { id: 3, title: '글로벌 OTT 서비스의 사용자 증가' },
                    { id: 4, title: '디지털 광고 시장의 트렌드와 전략' },
                    { id: 5, title: '인공지능 기반 미디어 플랫폼의 개발' },
                    { id: 6, title: '디지털 미디어 콘텐츠의 다양성과 사용자 경험' },
                ],
            },
            {
                id: 12,
                companyId: 42,
                companyIcon: '../../images/assets/company/company_ico_42.svg',
                companyName: 'data news',
                updatedDate: '08월 14일 03:00 직접 편집',
                mainNews: {
                    id: 42,
                    src: 'https://picsum.photos/500/300?img=42',
                    title: '글로벌 통신 산업의 디지털 전환과 새로운 비즈니스 모델',
                },
                news: [
                    { id: 1, title: '5G 네트워크와 디지털 통신 인프라의 발전' },
                    { id: 2, title: '디지털 플랫폼과 통신 기술의 융합' },
                    { id: 3, title: '클라우드 기반 통신 서비스와 경제적 효과' },
                    { id: 4, title: '글로벌 통신 산업의 디지털 전환 전략' },
                    { id: 5, title: '통신 네트워크의 스마트 시티 응용 사례' },
                    { id: 6, title: '5G 네트워크와 클라우드 통합 관리 시스템' },
                ],
            },
            {
                id: 13,
                companyId: 43,
                companyIcon: '../../images/assets/company/company_ico_43.svg',
                companyName: '한국대학신문',
                updatedDate: '08월 15일 04:00 직접 편집',
                mainNews: {
                    id: 43,
                    src: 'https://picsum.photos/500/300?img=43',
                    title: '글로벌 네트워크 보안 시장의 동향과 전망',
                },
                news: [
                    { id: 1, title: '5G 네트워크 보안의 글로벌 시장 성장' },
                    { id: 2, title: '사이버 공격과 네트워크 보안 전략' },
                    { id: 3, title: '클라우드 기반 보안 솔루션의 필요성' },
                    { id: 4, title: '글로벌 통신 사업자들의 보안 정책 강화' },
                    { id: 5, title: '5G 네트워크 보안의 새로운 기술 동향' },
                    { id: 6, title: '인공지능과 머신러닝을 활용한 보안 시스템' },
                ],
            },
            {
                id: 14,
                companyId: 44,
                companyIcon: '../../images/assets/company/company_ico_44.svg',
                companyName: '서울파이낸스',
                updatedDate: '08월 16일 05:00 직접 편집',
                mainNews: {
                    id: 44,
                    src: 'https://picsum.photos/500/300?img=44',
                    title: '5G 기술의 글로벌 보급과 통신 시장의 혁신',
                },
                news: [
                    { id: 1, title: '5G 네트워크의 글로벌 전망과 시장 성장' },
                    { id: 2, title: '5G 통신 기술과 산업 혁신' },
                    { id: 3, title: '스마트 시티와 5G 네트워크의 연계' },
                    { id: 4, title: '글로벌 통신 산업의 5G 투자 전략' },
                    { id: 5, title: '5G 네트워크의 기술적 도전 과제' },
                    { id: 6, title: '5G 보안과 네트워크 관리 시스템' },
                ],
            },
            {
                id: 15,
                companyId: 45,
                companyIcon: '../../images/assets/company/company_ico_45.svg',
                companyName: '엑스포츠뉴스',
                updatedDate: '08월 17일 06:00 직접 편집',
                isSubscribe: true,
                mainNews: {
                    id: 45,
                    src: 'https://picsum.photos/500/300?img=45',
                    title: '디지털 통신 기술과 AI의 융합 시대',
                },
                news: [
                    { id: 1, title: 'AI 기술의 통신 네트워크 응용 사례' },
                    { id: 2, title: '클라우드 플랫폼과 AI 기술의 적용' },
                    { id: 3, title: '5G 네트워크와 인공지능 보안 시스템' },
                    { id: 4, title: 'AI 기반 네트워크 최적화 기술' },
                    { id: 5, title: 'AI와 데이터 분석을 활용한 통신 네트워크' },
                    { id: 6, title: '5G 네트워크와 AI 기술의 새로운 사례' },
                ],
            },
            {
                id: 16,
                companyId: 46,
                companyIcon: '../../images/assets/company/company_ico_46.svg',
                companyName: '맥스무비',
                updatedDate: '08월 18일 07:00 직접 편집',
                mainNews: {
                    id: 46,
                    src: 'https://picsum.photos/500/300?img=46',
                    title: '5G 네트워크의 글로벌 보급과 경제적 효과',
                },
                news: [
                    { id: 1, title: '글로벌 5G 통신 시장의 성장과 전망' },
                    { id: 2, title: '5G 네트워크와 스마트 시티의 연계' },
                    { id: 3, title: '5G 네트워크의 산업 변화와 경쟁' },
                    { id: 4, title: '5G 기술과 디지털 경제의 통합' },
                    { id: 5, title: '5G 네트워크의 글로벌 표준화 동향' },
                    { id: 6, title: '5G 네트워크의 보안과 데이터 프라이버시' },
                ],
            },
            {
                id: 17,
                companyId: 47,
                companyIcon: '../../images/assets/company/company_ico_47.svg',
                companyName: 'OBS',
                updatedDate: '08월 19일 08:00 직접 편집',
                mainNews: {
                    id: 47,
                    src: 'https://picsum.photos/500/300?img=47',
                    title: '글로벌 통신 시장의 스마트 시티 기술과 혁신',
                },
                news: [
                    { id: 1, title: '스마트 시티 기술의 발전과 전망' },
                    { id: 2, title: '5G 네트워크와 스마트 시티 인프라 구축' },
                    { id: 3, title: '스마트 시티와 인공지능 기반 서비스' },
                    { id: 4, title: '스마트 시티 프로젝트의 글로벌 사례' },
                    { id: 5, title: '스마트 시티 기술과 환경 보호' },
                    { id: 6, title: '스마트 시티 네트워크의 보안과 데이터 관리' },
                ],
            },
            {
                id: 18,
                companyId: 48,
                companyIcon: '../../images/assets/company/company_ico_48.svg',
                companyName: '소년한국일보',
                updatedDate: '08월 20일 09:00 직접 편집',
                mainNews: {
                    id: 48,
                    src: 'https://picsum.photos/500/300?img=48',
                    title: '디지털 통신 시장의 AI 기술 적용과 효율성',
                },
                news: [
                    { id: 1, title: 'AI 기술과 통신 네트워크의 최신 개발 동향' },
                    { id: 2, title: 'AI 기반 네트워크 관리 시스템의 성과' },
                    { id: 3, title: '클라우드 기반 AI 플랫폼의 전략적 활용' },
                    { id: 4, title: '5G 네트워크와 AI 기술의 통합 사례' },
                    { id: 5, title: 'AI 기술의 네트워크 최적화와 자동화' },
                    { id: 6, title: 'AI 보안 시스템과 데이터 분석의 발전' },
                ],
            },
            {
                id: 19,
                companyId: 49,
                companyIcon: '../../images/assets/company/company_ico_49.svg',
                companyName: 'OSEN',
                updatedDate: '08월 21일 10:00 직접 편집',
                mainNews: {

                    id: 49,
                    src: 'https://picsum.photos/500/300?img=49',
                    title: '글로벌 네트워크 보안 시장의 성장과 전망',
                },
                news: [
                    { id: 1, title: '네트워크 보안 시스템의 혁신적 발전' },
                    { id: 2, title: '5G 보안의 기술적 도전 과제' },
                    { id: 3, title: 'AI 기반 네트워크 보안 시스템의 통합' },
                    { id: 4, title: '디지털 공격과 네트워크 보안 전략' },
                    { id: 5, title: '글로벌 통신 사업자들의 보안 투자 전략' },
                    { id: 6, title: '5G 네트워크와 보안 프로토콜' },
                ],
            },
            {
                id: 20,
                companyId: 50,
                companyIcon: '../../images/assets/company/company_ico_50.svg',
                companyName: '디지털타임스',
                updatedDate: '08월 22일 11:00 직접 편집',
                mainNews: {
                    id: 50,
                    src: 'https://picsum.photos/500/300?img=50',
                    title: '스마트 시티 기술과 5G 네트워크의 통합 시스템',
                },
                news: [
                    { id: 1, title: '5G 네트워크와 스마트 시티의 인프라 구축' },
                    { id: 2, title: '스마트 시티 기술의 글로벌 시장 전망' },
                    { id: 3, title: '5G 기술과 스마트 시티 서비스의 혁신' },
                    { id: 4, title: 'AI 기술과 스마트 시티 자동화 시스템' },
                    { id: 5, title: '스마트 시티 기술과 환경 보호' },
                    { id: 6, title: '스마트 시티 네트워크의 보안과 데이터 관리' },
                ],
            },
        ],
    },
    {
        category: '영자지',
        company: [
            {
                id: 1,
                companyId: 51,
                companyIcon: '../../images/assets/company/company_ico_51.svg',
                companyName: '미디어오늘',
                updatedDate: 'August 1, 10:00 AM (edited)',
                mainNews: {
                    id: 51,
                    src: 'https://picsum.photos/500/300?img=51',
                    title: 'Korean Economy Forecasts GDP Growth, Expectations of Economic Recovery',
                },
                news: [
                    { id: 1, title: 'Global Economic Situation and its Impact on the Korean Economy' },
                    { id: 2, title: 'Increase in Exports, Key Factors in Post-COVID Economic Recovery' },
                    { id: 3, title: 'Expected Impact of US Interest Rate Hikes on the Korean Economy' },
                    { id: 4, title: 'Rapid Growth in the Digital Currency Market and its Impact on the Financial Market' },
                    { id: 5, title: 'Concerns over Global Inflation Issues and Prospects for the Korean Economy' },
                    { id: 6, title: 'Predictions for Economic Growth Rate and Analysis of the Second Disaster Relief Fund' },
                ],
            },
            {
                id: 2,
                companyId: 52,
                companyIcon: '../../images/assets/company/company_ico_52.svg',
                companyName: '연합뉴스TV',
                updatedDate: 'August 2, 11:00 AM (edited)',
                mainNews: {
                    id: 52,
                    src: 'https://picsum.photos/500/300?img=52',
                    title: 'Technological Advancements in Digital Media Market',
                },
                news: [
                    { id: 1, title: 'Growth and Reader Response of Online News Platforms' },
                    { id: 2, title: 'New Strategies in Digital Media and Advertising Industry' },
                    { id: 3, title: 'Changes in User Behavior on Social Media Platforms' },
                    { id: 4, title: 'Competition and Strategies in Online News Subscription Services' },
                    { id: 5, title: 'Analysis and Utilization of User Data in Digital Media' },
                    { id: 6, title: 'Recommendation of Media Content Using AI and Machine Learning' },
                ],
            },
            {
                id: 3,
                companyId: 53,
                companyIcon: '../../images/assets/company/company_ico_53.svg',
                companyName: '한겨레',
                updatedDate: 'August 3, 12:00 PM (edited)',
                mainNews: {
                    id: 53,
                    src: 'https://picsum.photos/500/300?img=53',
                    title: 'Global Trends in Artificial Intelligence and Machine Learning',
                },
                news: [
                    { id: 1, title: 'AI Advancements and their Impact on Various Industries' },
                    { id: 2, title: 'Machine Learning Algorithms and their Applications' },
                    { id: 3, title: 'Ethical Considerations in AI Development and Deployment' },
                    { id: 4, title: 'Future Prospects of AI in Healthcare and Biotechnology' },
                    { id: 5, title: 'Integration of AI in Smart Cities and Urban Planning' },
                    { id: 6, title: 'Challenges and Opportunities in AI-driven Business Models' },
                ],
            },
            {
                id: 4,
                companyId: 54,
                companyIcon: '../../images/assets/company/company_ico_54.svg',
                companyName: 'Chosun Biz',
                updatedDate: 'August 4, 1:00 PM (edited)',
                mainNews: {
                    id: 54,
                    src: 'https://picsum.photos/500/300?img=54',
                    title: 'Future of E-commerce and Online Retail Trends',
                },
                news: [
                    { id: 1, title: 'E-commerce Growth and Consumer Behavior Shifts' },
                    { id: 2, title: 'Technological Innovations in Online Retail Platforms' },
                    { id: 3, title: 'Impact of Social Media Influencers on E-commerce Sales' },
                    { id: 4, title: 'Logistics and Supply Chain Challenges in E-commerce' },
                    { id: 5, title: 'Personalization and Customization in Online Shopping Experience' },
                    { id: 6, title: 'Emerging Trends in Cross-border E-commerce' },
                ],
            },
            {
                id: 5,
                companyId: 55,
                companyIcon: '../../images/assets/company/company_ico_55.svg',
                companyName: 'JTBC',
                updatedDate: 'August 5, 2:00 PM (edited)',
                mainNews: {
                    id: 55,
                    src: 'https://picsum.photos/500/300?img=55',
                    title: 'Environmental Sustainability Initiatives in Global Corporations',
                },
                news: [
                    { id: 1, title: 'Corporate Social Responsibility and Environmental Policies' },
                    { id: 2, title: 'Green Technologies and Renewable Energy Adoption' },
                    { id: 3, title: 'Circular Economy Models and Waste Management Strategies' },
                    { id: 4, title: 'Impact of Climate Change on Business Operations' },
                    { id: 5, title: 'Regulatory Trends and Compliance in Environmental Standards' },
                    { id: 6, title: 'Public Perception and Brand Reputation in Sustainability Efforts' },
                ],
            },
            {
                id: 6,
                companyId: 56,
                companyIcon: '../../images/assets/company/company_ico_56.svg',
                companyName: 'metro',
                updatedDate: 'August 6, 3:00 PM (edited)',
                mainNews: {
                    id: 56,
                    src: 'https://picsum.photos/500/300?img=56',
                    title: 'Impact of Cryptocurrency Regulation on Global Financial Markets',
                },
                news: [
                    { id: 1, title: 'Government Policies and Regulatory Frameworks in Cryptocurrency' },
                    { id: 2, title: 'Investor Sentiment and Market Volatility in Digital Assets' },
                    { id: 3, title: 'Blockchain Technology Applications beyond Cryptocurrency' },
                    { id: 4, title: 'Financial Institutions and their Approach to Digital Currency' },
                    { id: 5, title: 'Future Trends in Decentralized Finance (DeFi) Platforms' },
                    { id: 6, title: 'Risk Management Strategies in Crypto Investments' },
                ],
            },
            {
                id: 7,
                companyId: 57,
                companyIcon: '../../images/assets/company/company_ico_57.svg',
                companyName: '비즈한국',
                updatedDate: 'August 7, 4:00 PM (edited)',
                mainNews: {
                    id: 57,
                    src: 'https://picsum.photos/500/300?img=57',
                    title: 'Digital Transformation and Future of Work',
                },
                news: [
                    { id: 1, title: 'Remote Work Trends and Hybrid Workforce Strategies' },
                    { id: 2, title: 'Role of Artificial Intelligence in Workplace Automation' },
                    { id: 3, title: 'Employee Experience and Engagement in Digital Era' },
                    { id: 4, title: 'Skills Development and Reskilling in Tech-driven Industries' },
                    { id: 5, title: 'Cybersecurity Measures in Remote Work Environments' },
                    { id: 6, title: 'Impact of Digital Tools on Collaboration and Productivity' },
                ],
            },
            {
                id: 8,
                companyId: 58,
                companyIcon: '../../images/assets/company/company_ico_58.svg',
                companyName: '주간경향',
                updatedDate: 'August 8, 5:00 PM (edited)',
                mainNews: {
                    id: 58,
                    src: 'https://picsum.photos/500/300?img=58',
                    title: 'Future Trends in Artificial Intelligence and Robotics',
                },
                news: [
                    { id: 1, title: 'Advancements in AI Algorithms and Deep Learning Models' },
                    { id: 2, title: 'Applications of AI in Autonomous Vehicles and Robotics' },
                    { id: 3, title: 'Ethical Considerations in AI-driven Decision Making' },
                    { id: 4, title: 'Role of AI in Healthcare Diagnosis and Treatment' },
                    { id: 5, title: 'Challenges and Opportunities in AI-powered Smart Cities' },
                    { id: 6, title: 'Integration of AI with IoT and Edge Computing Technologies' },
                ],
            },
            {
                id: 9,
                companyId: 59,
                companyIcon: '../../images/assets/company/company_ico_59.svg',
                companyName: 'Forbes',
                updatedDate: 'August 9, 6:00 PM (edited)',
                mainNews: {
                    id: 59,
                    src: 'https://picsum.photos/500/300?img=59',
                    title: 'Emerging Trends in Virtual Reality and Augmented Reality',
                },
                news: [
                    { id: 1, title: 'VR/AR Applications in Gaming and Entertainment Industries' },
                    { id: 2, title: 'Educational Uses of VR/AR for Training and Simulation' },
                    { id: 3, title: 'Commercial and Retail Applications of Virtual Reality' },
                    { id: 4, title: 'Healthcare Innovations with Augmented Reality Tools' },
                    { id: 5, title: 'Future of VR/AR Hardware and Software Development' },
                    { id: 6, title: 'Challenges in VR/AR Content Creation and User Adoption' },
                ],
            },
            {
                id: 10,
                companyId: 60,
                companyIcon: '../../images/assets/company/company_ico_60.svg',
                companyName: 'TvReport',
                updatedDate: 'August 10, 7:00 PM (edited)',
                mainNews: {
                    id: 60,
                    src: 'https://picsum.photos/500/300?img=60',
                    title: 'Future of Digital Advertising and Marketing Strategies',
                },
                news: [
                    { id: 1, title: 'Personalized Advertising Campaigns and Customer Engagement' },
                    { id: 2, title: 'Impact of Data Privacy Regulations on Digital Marketing' },
                    { id: 3, title: 'Innovations in Programmatic Advertising Technologies' },
                    { id: 4, title: 'Social Media Influencer Marketing Trends' },
                    { id: 5, title: 'AI-powered Analytics and Predictive Marketing Tools' },
                    { id: 6, title: 'Cross-platform Integration in Digital Advertising Strategies' },
                ],
            },
        ],
    },
    {
        category: 'IT',
        company: [
            {
                id: 1,
                companyId: 61,
                companyIcon: '../../images/assets/company/company_ico_61.svg',
                companyName: '티브이데일리',
                updatedDate: '7월 14일 오전 09:00 직접 편집',
                mainNews: {
                    id: 61,
                    src: 'https://picsum.photos/500/300?img=61',
                    title: '인공지능 기술 발전, 기업 운영에 미치는 변화',
                },
                news: [
                    { id: 1, title: 'AI 기술이 고객 지원 서비스에 미치는 영향' },
                    { id: 2, title: '데이터 분석을 위한 머신 러닝 알고리즘의 진보' },
                    { id: 3, title: '가상 어시스턴트에 적용된 자연어 처리 기술의 응용' },
                    { id: 4, title: '예측 분석과 비즈니스 예측에 AI의 역할' },
                    { id: 5, title: '기업에서 AI 도입의 도전과 기회' },
                ],
            },
            {
                id: 2,
                companyId: 62,
                companyIcon: '../../images/assets/company/company_ico_62.svg',
                companyName: 'BBS News',
                updatedDate: '7월 15일 오전 10:00 직접 편집',
                mainNews: {
                    id: 62,
                    src: 'https://picsum.photos/500/300?img=62',
                    title: '사물인터넷 기술 발전과 스마트 시티 구축',
                },
                news: [
                    { id: 1, title: '스마트 시티 구축을 위한 IoT 기술의 적용' },
                    { id: 2, title: 'IoT가 생활 편의와 에너지 효율성에 미치는 영향' },
                    { id: 3, title: '빅데이터와의 통합으로 인한 IoT 시스템의 성능 향상' },
                    { id: 4, title: '도시 인프라 관리에서의 IoT 기술 활용 사례' },
                    { id: 5, title: '스마트 건물 관리와 안전 보안 강화를 위한 IoT 솔루션' },
                ],
            },
            {
                id: 3,
                companyId: 63,
                companyIcon: '../../images/assets/company/company_ico_63.svg',
                companyName: 'Monde diplomatique',
                updatedDate: '7월 16일 오전 11:00 직접 편집',
                mainNews: {
                    id: 63,
                    src: 'https://picsum.photos/500/300?img=63',
                    title: '블록체인 기술과 금융 산업의 혁신',
                },
                news: [
                    { id: 1, title: '디지털 자산 관리를 위한 블록체인 기술의 활용' },
                    { id: 2, title: '스마트 계약의 블록체인 기반 구현 사례' },
                    { id: 3, title: '금융 거래의 투명성 강화를 위한 블록체인 기술' },
                    { id: 4, title: '블록체인 기술이 은행 업무 프로세스에 미치는 영향' },
                    { id: 5, title: '블록체인 기술과 보안 토큰의 활용' },
                ],
            },
            {
                id: 4,
                companyId: 64,
                companyIcon: '../../images/assets/company/company_ico_64.svg',
                companyName: 'MK스포츠',
                updatedDate: '7월 17일 오전 09:30 직접 편집',
                mainNews: {
                    id: 64,
                    src: 'https://picsum.photos/500/300?img=64',
                    title: '빅데이터 분석과 기업 전략 개발',
                },
                news: [
                    { id: 1, title: '빅데이터 수집과 분석을 통한 시장 트렌드 파악' },
                    { id: 2, title: '고객 데이터 분석을 통한 개인 맞춤형 마케팅 전략' },
                    { id: 3, title: '예측 분석을 통한 비즈니스 운영 최적화 방안' },
                    { id: 4, title: '데이터 마이닝 기법과 비즈니스 인텔리전스 활용' },
                    { id: 5, title: '빅데이터 시스템 보안과 데이터 프라이버시 문제' },
                ],
            },
            {
                id: 5,
                companyId: 65,
                companyIcon: '../../images/assets/company/company_ico_65.svg',
                companyName: '텐아시아',
                updatedDate: '7월 18일 오전 10:30 직접 편집',
                mainNews: {
                    id: 65,
                    src: 'https://picsum.photos/500/300?img=65',
                    title: '사이버 보안과 데이터 프라이버시',
                },
                news: [
                    { id: 1, title: '사이버 공격 유형과 방어 전략의 진화' },
                    { id: 2, title: '개인정보 보호를 위한 데이터 보안 솔루션' },
                    { id: 3, title: 'IoT 기기의 보안 취약점과 대응 방안' },
                    { id: 4, title: '클라우드 보안의 최신 트렌드와 도전 과제' },
                    { id: 5, title: '디지털 신뢰성 확보를 위한 사이버 보안 전략' },
                ],
            },
            {
                id: 6,
                companyId: 66,
                companyIcon: '../../images/assets/company/company_ico_66.svg',
                companyName: '대한민국 정책브리핑',
                updatedDate: '7월 19일 오전 11:00 직접 편집',
                mainNews: {
                    id: 66,
                    src: 'https://picsum.photos/500/300?img=66',
                    title: '클라우드 컴퓨팅과 기업 IT 인프라',
                },
                news: [
                    { id: 1, title: '하이브리드 클라우드 환경에서의 IT 자원 최적화 전략' },
                    { id: 2, title: '클라우드 마이그레이션과 비즈니스 연속성 보장' },
                    { id: 3, title: '서버리스 컴퓨팅의 효율성과 비용 절감 효과' },
                    { id: 4, title: '멀티 클라우드 전략의 장점과 도전 과제' },
                    { id: 5, title: '클라우드 보안과 데이터 관리 전략' },
                ],
            },
            {
                id: 7,
                companyId: 67,
                companyIcon: '../../images/assets/company/company_ico_67.svg',
                companyName: '씨네21',
                updatedDate: '7월 20일 오전 09:30 직접 편집',
                mainNews: {
                    id: 67,
                    src: 'https://picsum.photos/500/300?img=67',
                    title: '사물인터넷과 스마트 홈 기술 발전',
                },
                news: [
                    { id: 1, title: '스마트 홈 디바이스와 IoT 기기의 연동성' },
                    { id: 2, title: 'AI 기반 스마트 홈 시스템의 향상된 사용자 경험' },
                    { id: 3, title: '가전 제품의 IoT 기능 추가와 생활 편의 증진' },
                    { id: 4, title: '스마트 시티와 스마트 홈 시스템의 통합 가능성' },
                    { id: 5, title: '스마트 거주 공간과 에너지 효율성 향상을 위한 기술 혁신' },
                ],
            },
            {
                id: 8,
                companyId: 68,
                companyIcon: '../../images/assets/company/company_ico_68.svg',
                companyName: '뉴스포스트',
                updatedDate: '7월 21일 오전 10:30 직접 편집',
                mainNews: {
                    id: 68,
                    src: 'https://picsum.photos/500/300?img=68',
                    title: '사이버 보안 위협과 기업 대응 전략',
                },
                news: [
                    { id: 1, title: '신종 사이버 공격 유형에 대한 대응 방안' },
                    { id: 2, title: '기업 보안 인프라 강화를 위한 최신 기술 솔루션' },
                    { id: 3, title: '정보 보안 전문가의 필수 역량과 역할' },
                    { id: 4, title: '사이버 보안 훈련과 교육의 중요성' },
                    { id: 5, title: '정보 보안 관리와 통합 보안 솔루션' },
                ],
            },
            {
                id: 9,
                companyId: 69,
                companyIcon: '../../images/assets/company/company_ico_69.svg',
                companyName: '정신의학신문',
                updatedDate: '7월 22일 오전 11:00 직접 편집',
                mainNews: {
                    id: 69,
                    src: 'https://picsum.photos/500/300?img=69',
                    title: '인공지능과 자율 주행차 기술 혁신',
                },
                news: [
                    { id: 1, title: 'AI 기술을 활용한 자율 주행차의 발전 동향' },
                    { id: 2, title: '자율 주행차 시스템의 안전성 평가와 개선 방향' },
                    { id: 3, title: '스마트 시티와 자율 주행차 시스템의 통합 가능성' },
                    { id: 4, title: 'AI 기반 운전 보조 시스템의 발전' },
                    { id: 5, title: '자율 주행차 보안 문제와 해결 전략' },
                ],
            },
            {
                id: 10,
                companyId: 70,
                companyIcon: '../../images/assets/company/company_ico_70.svg',
                companyName: '철강금속신문',
                updatedDate: '7월 23일 오전 09:30 직접 편집',
                mainNews: {
                    id: 70,
                    src: 'https://picsum.photos/500/300?img=70',
                    title: '클라우드 서비스와 데이터 관리 전략',
                },
                news: [
                    { id: 1, title: '멀티 클라우드 전략과 클라우드 데이터 이동 방안' },
                    { id: 2, title: '클라우드 데이터 보안을 위한 최신 툴과 솔루션' },
                    { id: 3, title: '클라우드 비용 관리와 최적화 전략' },
                    { id: 4, title: '클라우드 컴퓨팅의 확장성과 유연성' },
                    { id: 5, title: '하이브리드 클라우드 환경의 장점과 도전 과제' },
                ],
            },
        ],
    },
    {
        category: '스포츠/연예',
        company: [
            {
                id: 1,
                companyId: 71,
                companyIcon: '../../images/assets/company/company_ico_71.svg',
                companyName: 'Chosun71',
                updatedDate: '7월 14일 오전 09:00 직접 편집',
                mainNews: {
                    id: 71,
                    src: 'https://picsum.photos/500/300?img=71',
                    title: '올림픽 선수들의 역사적 순간들',
                },
                news: [
                    { id: 1, title: '올림픽 체조 부문에서의 한국 선수의 활약' },
                    { id: 2, title: '축구 유망주의 미래 전망과 기대' },
                    { id: 3, title: '배구 대표팀의 금메달 도전' },
                    { id: 4, title: '스포츠 스타들의 국제적 활동' },
                    { id: 5, title: '음악 콘서트 및 연예인 공연 소식' },
                ],
            },
            {
                id: 2,
                companyId: 72,
                companyIcon: '../../images/assets/company/company_ico_72.svg',
                companyName: '여성경제신문',
                updatedDate: '7월 15일 오전 10:00 직접 편집',
                mainNews: {
                    id: 72,
                    src: 'https://picsum.photos/500/300?img=72',
                    title: '드라마와 영화의 최신 소식',
                },
                news: [
                    { id: 1, title: '인기 드라마의 최신 에피소드 리뷰' },
                    { id: 2, title: '영화 박스 오피스 순위와 관객 반응' },
                    { id: 3, title: '연기자들의 최신 활동 소식' },
                    { id: 4, title: '드라마 OST와 음반 출시 소식' },
                    { id: 5, title: '연예인들의 SNS 트렌드와 팬 커뮤니케이션' },
                ],
            },
            {
                id: 3,
                companyId: 73,
                companyIcon: '../../images/assets/company/company_ico_73.svg',
                companyName: '한국일보',
                updatedDate: '7월 16일 오전 11:00 직접 편집',
                isSubscribe: true,
                mainNews: {
                    id: 73,
                    src: 'https://picsum.photos/500/300?img=73',
                    title: '스포츠 리그 및 대회의 최신 소식',
                },
                news: [
                    { id: 1, title: '축구 리그 경기 결과와 하이라이트' },
                    { id: 2, title: '농구 대회의 최신 업데이트' },
                    { id: 3, title: '야구 신인 리그의 주목할만한 플레이어' },
                    { id: 4, title: '골프 투어 대회의 최신 정보' },
                    { id: 5, title: '스포츠 인기 기자의 블로그 글' },
                ],
            },
            {
                id: 4,
                companyId: 74,
                companyIcon: '../../images/assets/company/company_ico_74.svg',
                companyName: 'sportalkorea',
                updatedDate: '7월 17일 오전 09:30 직접 편집',
                mainNews: {
                    id: 74,
                    src: 'https://picsum.photos/500/300?img=74',
                    title: '예술과 문화 이벤트 소식',
                },
                news: [
                    { id: 1, title: '미술 전시회와 아트 페스티벌 소식' },
                    { id: 2, title: '공연 예술의 최신 공연 일정과 리뷰' },
                    { id: 3, title: '문화 축제의 참여자 모집 소식' },
                    { id: 4, title: '클래식 음악 콘서트와 오페라 공연 소식' },
                    { id: 5, title: '책 출간과 문학 행사 소식' },
                ],
            },
            {
                id: 5,
                companyId: 75,
                companyIcon: '../../images/assets/company/company_ico_75.svg',
                companyName: '프레시안',
                updatedDate: '7월 18일 오전 10:30 직접 편집',
                mainNews: {
                    id: 75,
                    src: 'https://picsum.photos/500/300?img=75',
                    title: '유명 인사들의 최신 뉴스',
                },
                news: [
                    { id: 1, title: '연예계 인사들의 결혼 및 출산 소식' },
                    { id: 2, title: '스포츠 스타들의 최신 인터뷰 및 이야기' },
                    { id: 3, title: '영화 감독과 배우의 프로젝트 소식' },
                    { id: 4, title: '연예계 스캔들 및 루머 업데이트' },
                    { id: 5, title: '스포츠 인사들의 트레이닝 및 일상 생활 소식' },
                ],
            },
            {
                id: 6,
                companyId: 76,
                companyIcon: '../../images/assets/company/company_ico_76.svg',
                companyName: '노컷뉴스',
                updatedDate: '7월 19일 오전 11:00 직접 편집',
                mainNews: {
                    id: 76,
                    src: 'https://picsum.photos/500/300?img=76',
                    title: '게임과 엔터테인먼트 산업 동향',
                },
                news: [
                    { id: 1, title: '최신 게임 출시 일정과 업데이트 소식' },
                    { id: 2, title: '인기 온라인 게임의 최신 패치 내용' },
                    { id: 3, title: '모바일 게임 트렌드와 유망 콘텐츠 소개' },
                    { id: 4, title: '게임 개발자의 인터뷰 및 개발 이야기' },
                    { id: 5, title: '게임 시장 분석과 향후 전망' },
                ],
            },
            {
                id: 7,
                companyId: 77,
                companyIcon: '../../images/assets/company/company_ico_77.svg',
                companyName: 'The JoongAng',
                updatedDate: '7월 20일 오전 09:30 직접 편집',
                mainNews: {
                    id: 77,
                    src: 'https://picsum.photos/500/300?img=77',
                    title: '스포츠 토크 및 해설',
                },
                news: [
                    { id: 1, title: '스포츠 경기 해설과 전략 분석' },
                    { id: 2, title: '테니스 및 골프 경기 리뷰' },
                    { id: 3, title: '축구 팀 간의 전략적 비교' },
                    { id: 4, title: '농구 및 야구 플레이어 인터뷰' },
                    { id: 5, title: '스포츠 예측 및 토크 프로그램 소식' },
                ],
            },
            {
                id: 8,
                companyId: 78,
                companyIcon: '../../images/assets/company/company_ico_78.svg',
                companyName: '서울신문',
                updatedDate: '7월 21일 오전 10:00 직접 편집',
                mainNews: {
                    id: 78,
                    src: 'https://picsum.photos/500/300?img=78',
                    title: '연예계의 트렌드와 패션',
                },
                news: [
                    { id: 1, title: '인기 연예인의 패션 스타일과 트렌드' },
                    { id: 2, title: '프로모션 및 브랜드 협찬 소식' },
                    { id: 3, title: '연예계 인사들의 최신 SNS 업데이트' },
                    { id: 4, title: '패션 디자이너와 스타일리스트의 인터뷰' },
                    { id: 5, title: '연예계 스타일 아이콘의 생활 스타일' },
                ],
            },
            {
                id: 9,
                companyId: 79,
                companyIcon: '../../images/assets/company/company_ico_79.svg',
                companyName: '스포츠조선',
                updatedDate: '7월 22일 오전 11:00 직접 편집',
                mainNews: {
                    id: 79,
                    src: 'https://picsum.photos/500/300?img=79',
                    title: '스포츠 인사 및 레전드 이야기',
                },
                news: [
                    { id: 1, title: '스포츠 스타의 근황과 복귀 소식' },
                    { id: 2, title: '레전드 선수의 경력과 업적 회고' },
                    { id: 3, title: '스포츠 역사적 순간들의 리뷰' },
                    { id: 4, title: '스포츠 인사의 최신 뉴스 및 인터뷰' },
                    { id: 5, title: '스포츠 기자들의 전망과 예측' },
                ],
            },
            {
                id: 10,
                companyId: 80,
                companyIcon: '../../images/assets/company/company_ico_80.svg',
                companyName: '전자신문',
                updatedDate: '7월 23일 오전 09:30 직접 편집',
                mainNews: {
                    id: 80,
                    src: 'https://picsum.photos/500/300?img=80',
                    title: '연예계 인사의 생일 및 기념일 소식',
                },
                news: [
                    { id: 1, title: '인기 연예계 인사들의 생일 축하 소식' },
                    { id: 2, title: '연예계의 결혼 및 약혼 소식' },
                    { id: 3, title: '연예계 인사들의 다양한 기념일 소식' },
                    { id: 4, title: '연예계 스타들의 자선 활동 소식' },
                    { id: 5, title: '연예계 인사들의 개인 SNS 업데이트' },
                ],
            },
        ],
    },
    {
        category: '매거진/전문지',
        company: [
            {
                id: 1,
                companyId: 81,
                companyIcon: '../../images/assets/company/company_ico_81.svg',
                companyName: '천지일보',
                updatedDate: '07월 14일 09:00 직접 편집',
                mainNews: {
                    id: 81,
                    src: 'https://picsum.photos/500/300?img=81',
                    title: '최신 트렌드, 가을 패션과 스타일링 방법',
                },
                news: [
                    { id: 1, title: '2024 가을 시즌 새로운 트렌드 예측' },
                    { id: 2, title: '스타일리시한 코트와 완벽한 매치' },
                    { id: 3, title: '심플한 디자인의 액세서리 추천' },
                    { id: 4, title: '패션 아이템의 다양한 활용법 소개' },
                    { id: 5, title: '가을 컬러 팔레트와 조화로운 조합' },
                    { id: 6, title: '컬렉션 룩북과 스타일링 팁' },
                ],
            },
            {
                id: 2,
                companyId: 82,
                companyIcon: '../../images/assets/company/company_ico_82.svg',
                companyName: 'Bloter',
                updatedDate: '07월 15일 10:00 직접 편집',
                mainNews: {
                    id: 82,
                    src: 'https://picsum.photos/500/300?img=82',
                    title: '최고의 새로운 레스토랑과 요리 경험',
                },
                news: [
                    { id: 1, title: '세계 각국의 인기 요리와 그 특징 소개' },
                    { id: 2, title: '새로운 레스토랑의 메뉴와 인기 메뉴 추천' },
                    { id: 3, title: '요리의 기술적인 요소와 기법 소개' },
                    { id: 4, title: '다양한 요리 스타일과 특징적인 맛의 비밀' },
                    { id: 5, title: '각국의 전통 음식과 현지 요리의 매력 소개' },
                    { id: 6, title: '레스토랑 맛집 추천과 방문 전략' },
                ],
            },
            {
                id: 3,
                companyId: 83,
                companyIcon: '../../images/assets/company/company_ico_83.svg',
                companyName: 'KBS',
                updatedDate: '07월 16일 11:00 직접 편집',
                mainNews: {
                    id: 83,
                    src: 'https://picsum.photos/500/300?img=83',
                    title: '새로운 여행 목적지와 현지 문화 탐방',
                },
                news: [
                    { id: 1, title: '아름다운 자연 경치와 풍부한 문화 체험' },
                    { id: 2, title: '비밀스러운 숨은 관광지와 로컬 투어 추천' },
                    { id: 3, title: '특별한 여행 경험과 잊지 못할 순간들' },
                    { id: 4, title: '문화적으로 풍부한 지역의 이야기와 전통' },
                    { id: 5, title: '현지 인기 명소와 여행 팁' },
                    { id: 6, title: '사진 작가가 추천하는 최고의 촬영 스팟' },
                ],
            },
            {
                id: 4,
                companyId: 84,
                companyIcon: '../../images/assets/company/company_ico_84.svg',
                companyName: '동아일보',
                updatedDate: '07월 17일 09:30 직접 편집',
                mainNews: {
                    id: 84,
                    src: 'https://picsum.photos/500/300?img=84',
                    title: '최신 영화와 블록버스터 리뷰',
                },
                news: [
                    { id: 1, title: '2024 최고의 영화와 기대되는 블록버스터 소개' },
                    { id: 2, title: '주목할 만한 배우와 감독의 최신 작품 리뷰' },
                    { id: 3, title: '영화 스토리와 감정적인 요소 분석' },
                    { id: 4, title: '다양한 장르와 스타일의 영화 추천' },
                    { id: 5, title: '영화 제작 비하인드 스토리와 뒷이야기' },
                    { id: 6, title: '영화 음악과 사운드 트랙의 매력적인 면' },
                ],
            },
            {
                id: 5,
                companyId: 85,
                companyIcon: '../../images/assets/company/company_ico_85.svg',
                companyName: 'NEWSIS',
                updatedDate: '07월 18일 10:00 직접 편집',
                mainNews: {
                    id: 85,
                    src: 'https://picsum.photos/500/300?img=85',
                    title: '최신 기술과 혁신적인 제품 소개',
                },
                news: [
                    { id: 1, title: '기술적인 발전과 혁신적인 제품 소식' },
                    { id: 2, title: '인공지능과 빅데이터 기술의 응용 사례 소개' },
                    { id: 3, title: '스마트 기기와 새로운 기술의 활용 방안' },
                    { id: 4, title: '포스트 코로나 시대에 맞춘 디지털 트렌드' },
                    { id: 5, title: '현대 기술의 미래 전망과 트렌드 예측' },
                    { id: 6, title: '테크 뉴스와 혁신 기업의 최신 동향' },
                ],
            },
            {
                id: 6,
                companyId: 86,
                companyIcon: '../../images/assets/company/company_ico_86.svg',
                companyName: '한국경제',
                updatedDate: '07월 19일 11:00 직접 편집',
                mainNews: {
                    id: 86,
                    src: 'https://picsum.photos/500/300?img=86',
                    title: '최고의 미술과 문화 이벤트 소식',
                },
                news: [
                    { id: 1, title: '세계적으로 인정받는 아티스트와 작품 소개' },
                    { id: 2, title: '미술 전시회와 문화 행사의 주요 소식' },
                    { id: 3, title: '예술과 디자인의 새로운 트렌드 소개' },
                    { id: 4, title: '국제적인 문화 이벤트와 축제 소개' },
                    { id: 5, title: '아름다운 미술과 문화의 다양성 소개' },
                    { id: 6, title: '문화적인 경험과 예술적인 발견' },
                ],
            },
        ],
    },
    {
        category: '지역',
        company: [
            {
                id: 1,
                companyId: 87,
                companyIcon: '../../images/assets/company/company_ico_87.svg',
                companyName: '시사IN',
                updatedDate: '7월 20일 오전 09:30 직접 편집',
                mainNews: {
                    id: 87,
                    src: 'https://picsum.photos/500/300?img=87',
                    title: '광주광역시, 지역 경제 회복 전략 발표',
                },
                news: [
                    { id: 1, title: '광주광역시 지역 중소기업 지원 및 경제 활성화 계획' },
                    { id: 2, title: '광주광역시 지역 산업 클러스터 확대 및 개발 계획' },
                    { id: 3, title: '광주광역시 지역 문화 예술과 체육 활성화 계획' },
                    { id: 4, title: '광주광역시 지역 공공 인프라 및 환경 개선 계획' },
                    { id: 5, title: '광주광역시 지역 경제 협력 및 국제 마케팅 전략' },
                ],
            },
            {
                id: 2,
                companyId: 88,
                companyIcon: '../../images/assets/company/company_ico_88.svg',
                companyName: '산',
                updatedDate: '7월 21일 오전 10:00 직접 편집',
                mainNews: {
                    id: 88,
                    src: 'https://picsum.photos/500/300?img=88',
                    title: '울산광역시, 새로운 해양 미래 전략 발표',
                },
                news: [
                    { id: 1, title: '울산광역시 해양 산업 발전 및 미래 기술 전략 소식' },
                    { id: 2, title: '울산광역시 해양 생태 보전 및 지속 가능 발전 전략' },
                    { id: 3, title: '울산광역시 해양 관광 산업 활성화 및 홍보 계획' },
                    { id: 4, title: '울산광역시 해양 자원 개발 및 관리 전략 소식' },
                    { id: 5, title: '울산광역시 해양 교육 및 연구 인프라 강화 계획' },
                ],
            },
            {
                id: 3,
                companyId: 89,
                companyIcon: '../../images/assets/company/company_ico_89.svg',
                companyName: '독서신문',
                updatedDate: '7월 22일 오전 11:00 직접 편집',
                mainNews: {
                    id: 89,
                    src: 'https://picsum.photos/500/300?img=89',
                    title: '강원도, 지역 농산물 수출 확대 전략 발표',
                },
                news: [
                    { id: 1, title: '강원도 지역 특산 농산물의 해외 시장 개척 계획' },
                    { id: 2, title: '강원도 지역 농업 혁신 및 스마트 농업 기술 도입 계획' },
                    { id: 3, title: '강원도 지역 농업 인프라 및 생산 시스템 개선 계획' },
                    { id: 4, title: '강원도 지역 농산물의 품질 관리 및 마케팅 전략' },
                    { id: 5, title: '강원도 지역 농업 인력 양성 및 교육 지원 계획' },
                ],
            },
            {
                id: 4,
                companyId: 90,
                companyIcon: '../../images/assets/company/company_ico_90.svg',
                companyName: 'EconoTimes',
                updatedDate: '7월 23일 오전 09:30 직접 편집',
                mainNews: {
                    id: 90,
                    src: 'https://picsum.photos/500/300?img=90',
                    title: '제주특별자치도, 지역 관광 산업 활성화 전략 발표',
                },
                news: [
                    { id: 1, title: '제주특별자치도 지역 관광 인프라 확충 및 개선 계획' },
                    { id: 2, title: '제주특별자치도 지역 문화 자원 보호 및 활용 계획' },
                    { id: 3, title: '제주특별자치도 지역 관광 수출 활성화 및 글로벌 마케팅 전략' },
                    { id: 4, title: '제주특별자치도 지역 자연 보호 및 지속 가능 관리 전략' },
                    { id: 5, title: '제주특별자치도 지역 관광 산업과 지역 경제 발전 전략' },
                ],
            },
            {
                id: 5,
                companyId: 91,
                companyIcon: '../../images/assets/company/company_ico_91.svg',
                companyName: 'TJB',
                updatedDate: '7월 24일 오전 09:00 직접 편집',
                mainNews: {
                    id: 91,
                    src: 'https://picsum.photos/500/300?img=91',
                    title: '충청북도, 지역 문화 유산 보존 및 활용 전략 발표',
                },
                news: [
                    { id: 1, title: '충청북도 지역 전통 문화 유산 보존 및 복원 계획' },
                    { id: 2, title: '충청북도 지역 문화 예술 축제 및 행사 개최 계획' },
                    { id: 3, title: '충청북도 지역 전통 공예 및 고유 문화 콘텐츠 활성화 계획' },
                    { id: 4, title: '충청북도 지역 역사 탐방 및 문화 교육 프로그램 소식' },
                    { id: 5, title: '충청북도 지역 문화 유산을 활용한 지역 경제 활성화 전략' },
                ],
            },
            {
                id: 6,
                companyId: 92,
                companyIcon: '../../images/assets/company/company_ico_92.svg',
                companyName: '시사오늘 시사IN',
                updatedDate: '7월 25일 오전 10:00 직접 편집',
                mainNews: {
                    id: 92,
                    src: 'https://picsum.photos/500/300?img=92',
                    title: '경상북도, 새로운 농어촌 발전 전략 발표',
                },
                news: [
                    { id: 1, title: '경상북도 지역 농업 기술 혁신 및 스마트 농업 활성화 계획' },
                    { id: 2, title: '경상북도 지역 농산물의 품질 향상 및 수출 확대 계획' },
                    { id: 3, title: '경상북도 지역 농촌 생활 인프라 및 편의 시설 개선 계획' },
                    { id: 4, title: '경상북도 지역 농어촌 청년 일자리 창출 및 교육 지원 계획' },
                    { id: 5, title: '경상북도 지역 농어촌 문화 유산 보호 및 활용 전략' },
                ],
            },
            {
                id: 7,
                companyId: 93,
                companyIcon: '../../images/assets/company/company_ico_93.svg',
                companyName: '데일리한국',
                updatedDate: '7월 26일 오전 11:00 직접 편집',
                mainNews: {
                    id: 93,
                    src: 'https://picsum.photos/500/300?img=93',
                    title: '전라남도, 지역 관광 인프라 개선 계획 발표',
                },
                news: [
                    { id: 1, title: '전라남도 지역 관광명소 접근성 개선 및 주차 시설 확충 계획' },
                    { id: 2, title: '전라남도 지역 관광 콘텐츠 및 체험 프로그램 다양화 계획' },
                    { id: 3, title: '전라남도 지역 문화 자원 보호 및 관리 전략' },
                    { id: 4, title: '전라남도 지역 관광 산업과 지역 경제 발전 전략' },
                    { id: 5, title: '전라남도 지역 농어촌 체험 프로그램 및 생태 관광 확대 계획' },
                ],
            },
            {
                id: 8,
                companyId: 94,
                companyIcon: '../../images/assets/company/company_ico_94.svg',
                companyName: '뉴스토마토',
                updatedDate: '7월 27일 오전 09:30 직접 편집',
                mainNews: {
                    id: 94,
                    src: 'https://picsum.photos/500/300?img=94',
                    title: '경상남도, 산업 클러스터 확대 전략 발표',
                },
                news: [
                    { id: 1, title: '경상남도 지역 산업 클러스터 협력 네트워크 구축 계획' },
                    { id: 2, title: '경상남도 중소기업 지원 및 혁신 기업 육성 계획' },
                    { id: 3, title: '경상남도 지역 산업 기술 혁신 및 개발 전략' },
                    { id: 4, title: '경상남도 지역 산업 인프라 및 환경 보호 계획' },
                    { id: 5, title: '경상남도 지역 산업 클러스터 국제 경쟁력 강화 전략' },
                ],
            },
            {
                id: 9,
                companyId: 95,
                companyIcon: '../../images/assets/company/company_ico_95.svg',
                companyName: '에이블뉴스',
                updatedDate: '7월 28일 오전 10:00 직접 편집',
                mainNews: {
                    id: 95,
                    src: 'https://picsum.photos/500/300?img=95',
                    title: '제주특별자치도, 지역 환경 보호 및 에코 투어 프로젝트 발표',
                },
                news: [
                    { id: 1, title: '제주특별자치도 지역 자연 생태 보전 및 환경 보호 계획' },
                    { id: 2, title: '제주특별자치도 지역 생태 관광 및 환경 교육 프로그램 계획' },
                    { id: 3, title: '제주특별자치도 지역 해양 보호 및 섬 관리 전략' },
                    { id: 4, title: '제주특별자치도 지역 환경 인프라 및 에너지 효율성 개선 계획' },
                    { id: 5, title: '제주특별자치도 지역 환경 보호를 위한 지속 가능한 발전 전략' },
                ],
            },
        ],
    },
]