export const wholeCompanyData = [
    {
        id: 1,
        name: '회사1',
        icon: './assets/company/company_ico_1.svg',
        isSubscribed: false,
    },
    {
        id: 2,
        name: '회사2',
        icon: './assets/company/company_ico_2.svg',
        isSubscribed: false,
    },
    {
        id: 3,
        name: '회사3',
        icon: './assets/company/company_ico_3.svg',
        isSubscribed: false,
    },
    {
        id: 4,
        name: '회사4',
        icon: './assets/company/company_ico_4.svg',
        isSubscribed: false,
    },
    {
        id: 5,
        name: '회사5',
        icon: './assets/company/company_ico_5.svg',
        isSubscribed: false,
    },
    {
        id: 6,
        name: '회사6',
        icon: './assets/company/company_ico_6.svg',
        isSubscribed: false,
    },
    {
        id: 7,
        name: '회사7',
        icon: './assets/company/company_ico_7.svg',
        isSubscribed: false,
    },
    {
        id: 8,
        name: '회사8',
        icon: './assets/company/company_ico_8.svg',
        isSubscribed: false,
    },
    {
        id: 9,
        name: '회사9',
        icon: './assets/company/company_ico_9.svg',
        isSubscribed: false,
    },
    {
        id: 10,
        name: '회사10',
        icon: './assets/company/company_ico_10.svg',
        isSubscribed: false,
    },
    {
        id: 11,
        name: '회사11',
        icon: './assets/company/company_ico_11.svg',
        isSubscribed: false,
    },
    {
        id: 12,
        name: '회사12',
        icon: './assets/company/company_ico_12.svg',
        isSubscribed: false,
    },
    {
        id: 13,
        name: '회사13',
        icon: './assets/company/company_ico_13.svg',
        isSubscribed: false,
    },
    {
        id: 14,
        name: '회사14',
        icon: './assets/company/company_ico_14.svg',
        isSubscribed: false,
    },
    {
        id: 15,
        name: '회사15',
        icon: './assets/company/company_ico_15.svg',
        isSubscribed: false,
    },
    {
        id: 16,
        name: '회사16',
        icon: './assets/company/company_ico_16.svg',
        isSubscribed: false,
    },
    {
        id: 17,
        name: '회사17',
        icon: './assets/company/company_ico_17.svg',
        isSubscribed: false,
    },
    {
        id: 18,
        name: '회사18',
        icon: './assets/company/company_ico_18.svg',
        isSubscribed: false,
    },
    {
        id: 19,
        name: '회사19',
        icon: './assets/company/company_ico_19.svg',
        isSubscribed: false,
    },
    {
        id: 20,
        name: '회사20',
        icon: './assets/company/company_ico_20.svg',
        isSubscribed: false,
    },
    {
        id: 21,
        name: '회사21',
        icon: './assets/company/company_ico_21.svg',
        isSubscribed: false,
    },
    {
        id: 22,
        name: '회사22',
        icon: './assets/company/company_ico_22.svg',
        isSubscribed: false,
    },
    {
        id: 23,
        name: '회사23',
        icon: './assets/company/company_ico_23.svg',
        isSubscribed: false,
    },
    {
        id: 24,
        name: '회사24',
        icon: './assets/company/company_ico_24.svg',
        isSubscribed: false,
    },
    {
        id: 25,
        name: '회사25',
        icon: './assets/company/company_ico_25.svg',
        isSubscribed: false,
    },
    {
        id: 26,
        name: '회사26',
        icon: './assets/company/company_ico_26.svg',
        isSubscribed: false,
    },
    {
        id: 27,
        name: '회사27',
        icon: './assets/company/company_ico_27.svg',
        isSubscribed: false,
    },
    {
        id: 28,
        name: '회사28',
        icon: './assets/company/company_ico_28.svg',
        isSubscribed: false,
    },
    {
        id: 29,
        name: '회사29',
        icon: './assets/company/company_ico_29.svg',
        isSubscribed: false,
    },
    {
        id: 30,
        name: '회사30',
        icon: './assets/company/company_ico_30.svg',
        isSubscribed: false,
    },
    {
        id: 31,
        name: '회사31',
        icon: './assets/company/company_ico_31.svg',
        isSubscribed: false,
    },
    {
        id: 32,
        name: '회사32',
        icon: './assets/company/company_ico_32.svg',
        isSubscribed: false,
    },
    {
        id: 33,
        name: '회사33',
        icon: './assets/company/company_ico_33.svg',
        isSubscribed: false,
    },
    {
        id: 34,
        name: '회사34',
        icon: './assets/company/company_ico_34.svg',
        isSubscribed: false,
    },
    {
        id: 35,
        name: '회사35',
        icon: './assets/company/company_ico_35.svg',
        isSubscribed: false,
    },
    {
        id: 36,
        name: '회사36',
        icon: './assets/company/company_ico_36.svg',
        isSubscribed: false,
    },
    {
        id: 37,
        name: '회사37',
        icon: './assets/company/company_ico_37.svg',
        isSubscribed: false,
    },
    {
        id: 38,
        name: '회사38',
        icon: './assets/company/company_ico_38.svg',
        isSubscribed: false,
    },
    {
        id: 39,
        name: '회사39',
        icon: './assets/company/company_ico_39.svg',
        isSubscribed: false,
    },
    {
        id: 40,
        name: '회사40',
        icon: './assets/company/company_ico_40.svg',
        isSubscribed: false,
    },
    {
        id: 41,
        name: '회사41',
        icon: './assets/company/company_ico_41.svg',
        isSubscribed: false,
    },
    {
        id: 42,
        name: '회사42',
        icon: './assets/company/company_ico_42.svg',
        isSubscribed: false,
    },
    {
        id: 43,
        name: '회사43',
        icon: './assets/company/company_ico_43.svg',
        isSubscribed: false,
    },
    {
        id: 44,
        name: '회사44',
        icon: './assets/company/company_ico_44.svg',
        isSubscribed: false,
    },
    {
        id: 45,
        name: '회사45',
        icon: './assets/company/company_ico_45.svg',
        isSubscribed: false,
    },
    {
        id: 46,
        name: '회사46',
        icon: './assets/company/company_ico_46.svg',
        isSubscribed: false,
    },
    {
        id: 47,
        name: '회사47',
        icon: './assets/company/company_ico_47.svg',
        isSubscribed: false,
    },
    {
        id: 48,
        name: '회사48',
        icon: './assets/company/company_ico_48.svg',
        isSubscribed: false,
    },
    {
        id: 49,
        name: '회사49',
        icon: './assets/company/company_ico_49.svg',
        isSubscribed: false,
    },
    {
        id: 50,
        name: '회사50',
        icon: './assets/company/company_ico_50.svg',
        isSubscribed: false,
    },
    {
        id: 51,
        name: '회사51',
        icon: './assets/company/company_ico_51.svg',
        isSubscribed: false,
    },
    {
        id: 52,
        name: '회사52',
        icon: './assets/company/company_ico_52.svg',
        isSubscribed: false,
    },
    {
        id: 53,
        name: '회사53',
        icon: './assets/company/company_ico_53.svg',
        isSubscribed: false,
    },
    {
        id: 54,
        name: '회사54',
        icon: './assets/company/company_ico_54.svg',
        isSubscribed: false,
    },
    {
        id: 55,
        name: '회사55',
        icon: './assets/company/company_ico_55.svg',
        isSubscribed: false,
    },
    {
        id: 56,
        name: '회사56',
        icon: './assets/company/company_ico_56.svg',
        isSubscribed: false,
    },
    {
        id: 57,
        name: '회사57',
        icon: './assets/company/company_ico_57.svg',
        isSubscribed: false,
    },
    {
        id: 58,
        name: '회사58',
        icon: './assets/company/company_ico_58.svg',
        isSubscribed: false,
    },
    {
        id: 59,
        name: '회사59',
        icon: './assets/company/company_ico_59.svg',
        isSubscribed: false,
    },
    {
        id: 60,
        name: '회사60',
        icon: './assets/company/company_ico_60.svg',
        isSubscribed: false,
    },
    {
        id: 61,
        name: '회사61',
        icon: './assets/company/company_ico_61.svg',
        isSubscribed: false,
    },
    {
        id: 62,
        name: '회사62',
        icon: './assets/company/company_ico_62.svg',
        isSubscribed: false,
    },
    {
        id: 63,
        name: '회사63',
        icon: './assets/company/company_ico_63.svg',
        isSubscribed: false,
    },
    {
        id: 64,
        name: '회사64',
        icon: './assets/company/company_ico_64.svg',
        isSubscribed: false,
    },
    {
        id: 65,
        name: '회사65',
        icon: './assets/company/company_ico_65.svg',
        isSubscribed: false,
    },
    {
        id: 66,
        name: '회사66',
        icon: './assets/company/company_ico_66.svg',
        isSubscribed: false,
    },
    {
        id: 67,
        name: '회사67',
        icon: './assets/company/company_ico_67.svg',
        isSubscribed: false,
    },
    {
        id: 68,
        name: '회사68',
        icon: './assets/company/company_ico_68.svg',
        isSubscribed: false,
    },
    {
        id: 69,
        name: '회사69',
        icon: './assets/company/company_ico_69.svg',
        isSubscribed: false,
    },
    {
        id: 70,
        name: '회사70',
        icon: './assets/company/company_ico_70.svg',
        isSubscribed: false,
    },
    {
        id: 71,
        name: '회사71',
        icon: './assets/company/company_ico_71.svg',
        isSubscribed: false,
    },
    {
        id: 72,
        name: '회사72',
        icon: './assets/company/company_ico_72.svg',
        isSubscribed: false,
    },
    {
        id: 73,
        name: '회사73',
        icon: './assets/company/company_ico_73.svg',
        isSubscribed: false,
    },
    {
        id: 74,
        name: '회사74',
        icon: './assets/company/company_ico_74.svg',
        isSubscribed: false,
    },
    {
        id: 75,
        name: '회사75',
        icon: './assets/company/company_ico_75.svg',
        isSubscribed: false,
    },
    {
        id: 76,
        name: '회사76',
        icon: './assets/company/company_ico_76.svg',
        isSubscribed: false,
    },
    {
        id: 77,
        name: '회사77',
        icon: './assets/company/company_ico_77.svg',
        isSubscribed: false,
    },
    {
        id: 78,
        name: '회사78',
        icon: './assets/company/company_ico_78.svg',
        isSubscribed: false,
    },
    {
        id: 79,
        name: '회사79',
        icon: './assets/company/company_ico_79.svg',
        isSubscribed: false,
    },
    {
        id: 80,
        name: '회사80',
        icon: './assets/company/company_ico_80.svg',
        isSubscribed: false,
    },
    {
        id: 81,
        name: '회사81',
        icon: './assets/company/company_ico_81.svg',
        isSubscribed: false,
    },
    {
        id: 82,
        name: '회사82',
        icon: './assets/company/company_ico_82.svg',
        isSubscribed: false,
    },
    {
        id: 83,
        name: '회사83',
        icon: './assets/company/company_ico_83.svg',
        isSubscribed: false,
    },
    {
        id: 84,
        name: '회사84',
        icon: './assets/company/company_ico_84.svg',
        isSubscribed: false,
    },
    {
        id: 85,
        name: '회사85',
        icon: './assets/company/company_ico_85.svg',
        isSubscribed: false,
    },
    {
        id: 86,
        name: '회사86',
        icon: './assets/company/company_ico_86.svg',
        isSubscribed: false,
    },
    {
        id: 87,
        name: '회사87',
        icon: './assets/company/company_ico_87.svg',
        isSubscribed: false,
    },
    {
        id: 88,
        name: '회사88',
        icon: './assets/company/company_ico_88.svg',
        isSubscribed: false,
    },
    {
        id: 89,
        name: '회사89',
        icon: './assets/company/company_ico_89.svg',
        isSubscribed: false,
    },
    {
        id: 90,
        name: '회사90',
        icon: './assets/company/company_ico_90.svg',
        isSubscribed: false,
    },
    {
        id: 91,
        name: '회사91',
        icon: './assets/company/company_ico_91.svg',
        isSubscribed: false,
    },
    {
        id: 92,
        name: '회사92',
        icon: './assets/company/company_ico_92.svg',
        isSubscribed: false,
    },
    {
        id: 93,
        name: '회사93',
        icon: './assets/company/company_ico_93.svg',
        isSubscribed: false,
    },
    {
        id: 94,
        name: '회사94',
        icon: './assets/company/company_ico_94.svg',
        isSubscribed: false,
    },
    {
        id: 95,
        name: '회사95',
        icon: './assets/company/company_ico_95.svg',
        isSubscribed: false,
    },
    {
        id: 96,
        name: '회사96',
        icon: './assets/company/company_ico_96.svg',
        isSubscribed: false,
    },
]

export const getCompanyDataByPage = (page) => {
    const itemsPerPage = 24
    const startIndex = (page - 1) * itemsPerPage
    const endIndex = startIndex + itemsPerPage
    return wholeCompanyData.slice(startIndex, endIndex)
}

export const getMaxPage = () => {
    const itemsPerPage = 24
    return Math.ceil(wholeCompanyData.length / itemsPerPage)
}
